### ISSUE TITLE
NetInjector Support Net5 and above?

### ISSUE THREAD

**Issue by chinasmu** [mgaffigan/Esatto.Win32#1]

**Comment by chinasmu** [comment]
Looks like the remote progress only support net framework.
Will you consider update to Net5 and above？

**Comment by mgaffigan** [comment]
Hi @chinasmu,

You can historically inject from a .Net 5 project to a .Net Framework app.  I've added support for injecting *to* a .Net 3-8 app in version 3.0.16.  Let me know if you run into any trouble.
